/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_GO_IROH__
#define __RUST_GO_IROH__
#ifdef __cplusplus
extern "C" {
#endif

/** <No documentation available> */
typedef struct EndpointBuilder EndpointBuilder_t;


#include <stdbool.h>

/** <No documentation available> */
bool
iroh_builder_add_alpn (
    EndpointBuilder_t const * builder,
    char const * alpn);

/** <No documentation available> */
void
iroh_builder_apply_minimal (
    EndpointBuilder_t const * builder);

/** <No documentation available> */
void
iroh_builder_apply_n0 (
    EndpointBuilder_t const * builder);

/** <No documentation available> */
bool
iroh_builder_bind_addr (
    EndpointBuilder_t const * builder,
    char const * addr);

/** <No documentation available> */
EndpointBuilder_t *
iroh_builder_new (void);


#include <stddef.h>
#include <stdint.h>

/** <No documentation available> */
void
iroh_builder_relay_mode (
    EndpointBuilder_t const * builder,
    uint8_t mode);

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_uint8 {
    /** <No documentation available> */
    uint8_t * ptr;

    /** <No documentation available> */
    size_t len;

    /** <No documentation available> */
    size_t cap;
} Vec_uint8_t;

/** <No documentation available> */
bool
iroh_builder_secret_key (
    EndpointBuilder_t const * builder,
    Vec_uint8_t key);

/** <No documentation available> */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum Preset {
    /** <No documentation available> */
    PRESET_NONE = 0,
    /** <No documentation available> */
    PRESET_N0 = 1,
    /** <No documentation available> */
    PRESET_MINIMAL = 2,
    /** <No documentation available> */
    PRESET_N0_DISABLE_RELAY = 3,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
Preset_t;

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_Vec_uint8 {
    /** <No documentation available> */
    Vec_uint8_t * ptr;

    /** <No documentation available> */
    size_t len;

    /** <No documentation available> */
    size_t cap;
} Vec_Vec_uint8_t;

/** <No documentation available> */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum RelayModeFFI {
    /** \brief
     *  Disable relay servers completely.
     *  This means that neither listening nor dialing relays will be available.
     */
    RELAY_MODE_F_F_I_DISABLED = 0,
    /** \brief
     *  Use the default relay map, with production relay servers from n0.
     *
     *  See [`crate::defaults::prod`] for the severs used.
     */
    RELAY_MODE_F_F_I_DEFAULT = 1,
    /** \brief
     *  Use the staging relay servers from n0.
     */
    RELAY_MODE_F_F_I_STAGING = 2,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
RelayModeFFI_t;

/** <No documentation available> */
typedef struct EndpointOptions {
    /** \brief
     *  Preset that configures the endpoint builder. Defaults to [`Preset::N0`].
     */
    Preset_t preset;

    /** \brief
     *  Override the address the endpoint binds to. Accepts any standard
     *  `host:port` form (IPv4 or IPv6).
     */
    Vec_uint8_t bind_addr;

    /** \brief
     *  Provide a specific secret key, identifying this endpoint. Must be 32 bytes long.
     */
    Vec_uint8_t secret_key;

    /** \brief
     *  ALPN protocols advertised on the underlying TLS handshake. Independent of
     *  the per-protocol handlers in `protocols`; useful for client-only setups
     *  or for declaring extra ALPNs.
     */
    Vec_Vec_uint8_t alpns;

    /** \brief
     *  Override which relays the endpoint uses. Defaults to whatever the
     *  chosen [`Preset`] configures.
     */
    RelayModeFFI_t relay_mode;
} EndpointOptions_t;

/** <No documentation available> */
typedef struct Endpoint Endpoint_t;

/** <No documentation available> */
Endpoint_t *
iroh_endpoint_bind (
    EndpointOptions_t * options);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_GO_IROH__ */
